[package]
name = "twitter-bot-rs"
version = "0.1.0"
authors = ["Julien Delange <julien@gunnm.org>"]

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
tokio-core = "0.1.12"
hyper = "0.11.16"
hyper-tls = "0.1.2"
futures = "0.1"
oauth-client = "0.3"
twitter-api = "*"
